/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    courses: Course;
    instructors: Instructor;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    instructors: InstructorsSelect<false> | InstructorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    home: Home;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Select the users date of birth.
   */
  dob?: string | null;
  state?: string | null;
  /**
   * Only users with the "Admin" role can access the CMS.
   */
  role: 'admin' | 'user';
  enrollments: {
    course: number | Course;
    batch: string;
    /**
     * Enrollment date of the batch.
     */
    enrollmentDate: string;
    price: number;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * Auto-generated from the title, but can be edited.
   */
  slug: string;
  description: string;
  image: number | Media;
  rating: number;
  review: number;
  student: number;
  price: number;
  comparePrice: number;
  category: string;
  instructor: number | Instructor;
  /**
   * Example: "10 hours", "3 weeks", "Self-paced", etc.
   */
  duration: string;
  level: 'beginner' | 'intermediate' | 'advanced';
  whatYouLearnPoints: {
    title: string;
    id?: string | null;
  }[];
  skills: {
    title: string;
    id?: string | null;
  }[];
  reviews: {
    rating: string;
    reviewer: string;
    review: string;
    id?: string | null;
  }[];
  batches: {
    name: string;
    /**
     * Start date of the batch.
     */
    startDate: string;
    /**
     * End date of the batch.
     */
    endDate: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors".
 */
export interface Instructor {
  id: number;
  name: string;
  bio: string;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Auto-generated from the title, but can be edited.
   */
  slug: string;
  /**
   * Only users with the "Admin" role can access the CMS.
   */
  layout: 'about' | 'contact' | 'courses' | 'course-detail';
  metaTitle: string;
  metaDescription: string;
  blocks?:
    | (
        | {
            sectionHeading: {
              badge: string;
              title: string;
              subtitle?: string | null;
            };
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutUs';
          }
        | {
            mission?: string | null;
            vision?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'missionVision';
          }
        | {
            sectionHeading: {
              badge: string;
              title: string;
              subtitle?: string | null;
            };
            members?:
              | {
                  name: string;
                  designation?: string | null;
                  photo?: (number | null) | Media;
                  bio?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'courseListing';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'courseDetailBanner';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'courseDetail';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            title: string;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'banner';
          }
        | {
            sectionHeading: {
              badge: string;
              title: string;
              subtitle?: string | null;
            };
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            sectionHeading: {
              badge: string;
              title: string;
              subtitle?: string | null;
            };
            description?: string | null;
            primaryAction: {
              label: string;
              href: string;
            };
            secondaryAction: {
              label: string;
              href: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'promoBanner';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'instructors';
        value: number | Instructor;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  dob?: T;
  state?: T;
  role?: T;
  enrollments?:
    | T
    | {
        course?: T;
        batch?: T;
        enrollmentDate?: T;
        price?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?: T;
  metaTitle?: T;
  metaDescription?: T;
  blocks?:
    | T
    | {
        aboutUs?:
          | T
          | {
              sectionHeading?:
                | T
                | {
                    badge?: T;
                    title?: T;
                    subtitle?: T;
                  };
              content?: T;
              id?: T;
              blockName?: T;
            };
        missionVision?:
          | T
          | {
              mission?: T;
              vision?: T;
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              sectionHeading?:
                | T
                | {
                    badge?: T;
                    title?: T;
                    subtitle?: T;
                  };
              members?:
                | T
                | {
                    name?: T;
                    designation?: T;
                    photo?: T;
                    bio?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        courseListing?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        courseDetailBanner?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        courseDetail?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              sectionHeading?:
                | T
                | {
                    badge?: T;
                    title?: T;
                    subtitle?: T;
                  };
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        promoBanner?:
          | T
          | {
              sectionHeading?:
                | T
                | {
                    badge?: T;
                    title?: T;
                    subtitle?: T;
                  };
              description?: T;
              primaryAction?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryAction?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  rating?: T;
  review?: T;
  student?: T;
  price?: T;
  comparePrice?: T;
  category?: T;
  instructor?: T;
  duration?: T;
  level?: T;
  whatYouLearnPoints?:
    | T
    | {
        title?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        title?: T;
        id?: T;
      };
  reviews?:
    | T
    | {
        rating?: T;
        reviewer?: T;
        review?: T;
        id?: T;
      };
  batches?:
    | T
    | {
        name?: T;
        startDate?: T;
        endDate?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors_select".
 */
export interface InstructorsSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  metaTitle: string;
  metaDescription: string;
  blocks?:
    | (
        | {
            title: string;
            titleHighlight: string;
            subtitle?: string | null;
            image?: (number | null) | Media;
            primaryAction: {
              label: string;
              href: string;
            };
            secondaryAction: {
              label: string;
              href: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeBanner';
          }
        | {
            sectionHeading: {
              badge: string;
              title: string;
              subtitle?: string | null;
            };
            features: {
              title: string;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'feature';
          }
        | {
            sectionHeading: {
              badge: string;
              title: string;
              subtitle?: string | null;
            };
            image?: (number | null) | Media;
            points: {
              title: string;
              description?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'whyChooseUs';
          }
        | {
            sectionHeading: {
              badge: string;
              title: string;
              subtitle?: string | null;
            };
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
      )[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  quickItems?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  blocks?:
    | T
    | {
        homeBanner?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              subtitle?: T;
              image?: T;
              primaryAction?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryAction?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        feature?:
          | T
          | {
              sectionHeading?:
                | T
                | {
                    badge?: T;
                    title?: T;
                    subtitle?: T;
                  };
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whyChooseUs?:
          | T
          | {
              sectionHeading?:
                | T
                | {
                    badge?: T;
                    title?: T;
                    subtitle?: T;
                  };
              image?: T;
              points?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              sectionHeading?:
                | T
                | {
                    badge?: T;
                    title?: T;
                    subtitle?: T;
                  };
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  quickItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}